title: I-Sheng "Ethan" Fang
logo: ./logo.jpg
description: DeepLearning X Typography X Photography
theme: jekyll-theme-minimal
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-KGB67FZW0F"
