title: I-Sheng Fang
logo: ./logo.jpg
# description: DeepLearning X Typography X Photography
theme: jekyll-theme-minimal
google_analytics: "G-KGB67FZW0F"
github:
  is_user_page: true
  is_project_page: false